### ISSUE TITLE
Made it work using Tab + Tab shortcut

### ISSUE THREAD

**Issue by ijoel92** [OnlyLys/Leaper#10]
This may be useful for anyone:

I installed the extension and it wasn't working for me. I don't know the specific reason why but I replaced the keyboard shortcut for "Tab + Tab" and it made it work. My guess is the Intellisense configuration is clashing with the extension.

**Comment by OnlyLys** [comment]
> replaced the keyboard shortcut for "Tab + Tab"

Hi could you clarify what you meant by this? Did you mean that you changed the key binding of the "leaper.leap" command from `Tab` to `Tab + Tab`?

If I had to guess, it's likely that the `Tab` keybinding from another extension is clashing with this one. vscode handles keybindings by generating one huge list of all keybindings (with the editor default ones coming first, followed by third party extension ones). So when you press `Tab`, it searches the list in reverse to find the first match for `Tab`. However, as I understand it, there's no way for extension authors to predict where in the list their keybindings will end up, so clashes and unexpected behavior like this are bound to happen. 

I hope it's no trouble for you to describe in more detail what is happening.

**Comment by BatD2** [comment]
I love the extension but it suddenly stopped working and I can find any reson. appart from recent vscode update. 
I tried remove any other "tab" shortcut from the keymapping, but leaper still did not work. It works ok when I give it a different kemapping, but not with tab.

**Comment by OnlyLys** [comment]
@BatD2 Hi there, please ensure that the keybinding has the [proper when clause contexts](https://github.com/OnlyLys/Leaper/blob/632e71baf1900db2bb1ab7dd9cede924d9013b66/package.json#L712).

The first two when clause contexts `leaper.inLeaperMode && leaper.hasLineOfSight` are essential because the extension constantly toggles those contexts on and off so that the `leaper.leap` command (bound to `Tab` by default) is only enabled whenever there is a pair to jump out of.

However, if the `leaper.leap` command is working when you have it mapped to another key, that means the extension is correctly detecting pairs and correctly toggling the `leaper.inLeaperMode && leaper.hasLineOfSight` contexts. So the issue is most likely some other extension or command intercepting the `Tab` key before it is received by this extension. 

If you could, please check whether there are any conflicts for the `Tab` key. There is an [official guide on how to do so](https://code.visualstudio.com/docs/getstarted/keybindings#_detecting-keybinding-conflicts).
