### ISSUE TITLE
Conflict with emmet.triggerExpansionOnTab

### ISSUE THREAD

**Issue by charsboo** [OnlyLys/Leaper#4]
When `emmet.triggerExpansionOnTab` is set to `true`, this extension does not behave as intended (i.e., it does not leap out of autoclosing pair).

**Comment by ctf0** [comment]
https://github.com/OnlyLys/Leaper/blob/ad944edd56744187d90ea82f09d22f9d8b7b38db/package.json#L78-L82

**Comment by OnlyLys** [comment]
Hi I'm really sorry for the super late reply. 

The issue was that I mistakenly had this `!config.emmet.triggerExpansionOnTab` in the `when` clause of the default `leaper.leap` keybinding.

I thought that `config.emmet.triggerExpansionOnTab` would be a keybinding context that is only `true` when there is an emmet to expand (for instance, other VS Code contexts like `editorHasSelection` will only be `true` when there is a selection in the editor). The intention was to have the `leaper.leap` key not interfere whenever there is an emmet that can be expanded.

**But my assumption was incorrect**. `config.emmet.triggerExpansionOnTab`  is actually a persistent context, meaning if you turned it on in VS Code's settings then it will always be `true`, and the `leaper.leap` default keybinding will be permanently disabled.

In any case I have removed it in version `0.6.0`, which I'll upload shortly.

--------------------------------

Edit: And in fact the keybinding context that I was looking for such that 

> The intention was to have the `leaper.leap` key not interfere whenever there is an emmet that can be expanded.

was the `!suggestWidgetVisible` context that's already being used, since emmet expansion suggestions use the same quick suggestion widget as the other things like snippets and language auto completion.
