### ISSUE TITLE
How to use Enter key instead of tab

### ISSUE THREAD

**Issue by Freiza** [OnlyLys/Leaper#6]
How to use Enter key instead of tab to get out of the parenthesis?

**Comment by OnlyLys** [comment]
Hi! 

You need to rebind the `leaper.leap` command to the `Enter` key. 

Note that because the `Enter` key is used for many other things, rebinding a command to `Enter` might conflict with other commands that might use `Enter`. You might have to play around with the `when` clause of the keybinding to make sure it doesn't conflict with anything else. Other than the two contexts that start with `leaper.`, you are free to remove the other contexts or add new ones to get the desired behavior.

Microsoft has a page all about keybindings that might be helpful to understand this: https://code.visualstudio.com/docs/getstarted/keybindings

Feel free to ask any questions if you need more help!
